//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAspMvcEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Article
    {
        public Article()
        {
            this.Commandes = new HashSet<Commande>();
        }
        [DataMember]
        public int NumArticle { get; set; }
        [DataMember]
        public string Designation { get; set; }
        [DataMember]
        public Nullable<int> PrixU { get; set; }
        [DataMember]
        public Nullable<int> Stock { get; set; }
        [DataMember]
        public string Photo { get; set; }
        [DataMember]
        public Nullable<int> RefCat { get; set; }
        [DataMember]

        public virtual ICollection<Commande> Commandes { get; set; }
        [DataMember]
        public virtual Categorie Categorie { get; set; }
    }
}
