//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAspMvcEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference =true)]
    public partial class Client
    {
        public Client()
        {
            this.Commandes = new HashSet<Commande>();
        }
      [DataMember]
        public int NumClient { get; set; }
        [DataMember]
        public string Login { get; set; }
        [DataMember]
        public string MptPass { get; set; }
        [DataMember]
        public string Nom { get; set; }
        [DataMember]
        public string Prenom { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Ville { get; set; }
        [DataMember]
        public string Tel { get; set; }
        [DataMember]

        public virtual ICollection<Commande> Commandes { get; set; }
    }
}
